name: personal-template

include:
  - ./dockerfiles/database.compose.yaml
  - ./dockerfiles/kafka.compose.yaml
  # - ./dockerfiles/hoppscotch.compose.yaml
  # - ./dockerfiles/mail-server.compose.yaml
  # - ./dockerfiles/hardened-image.compose.yaml

# services:
#   sonarqube:
#     container_name: SonarQube
#     restart: on-failure
#     image: sonarqube:community
#     profiles: [ sonarqube ]
#     environment:
#       SONAR_JDBC_URL: jdbc:postgresql://database:5432/pgdb
#       SONAR_JDBC_USERNAME: projectpg
#       SONAR_JDBC_PASSWORD: pguser
#     ports:
#       - 9001:9000
#     volumes:
#       - sonarqube_data:/opt/data/sonarqube/data
#       - sonarqube_logs:/opt/data/sonarqube/logs
#       - sonarqube_extensions:/opt/data/sonarqube/extensions
#     depends_on:
#       - database
#     networks:
#       - sonarqube_network

#   app-service-sonarscan:
#     container_name: AppServiceSonarScan
#     image: sonarsource/sonar-scanner-cli:latest
#     restart: on-failure
#     profiles: [ sonarqube ]
#     environment:
#       SONAR_HOST_URL: http://sonarqube:9000
#       SONAR_TOKEN: sqa_a063cfa4dd7cf325bffcc835315a544565b1d723
#     volumes:
#       - ./SpringProject/projects/app-service/:/usr/src/
#     depends_on:
#       - sonarqube
#       - database
#     networks:
#       - sonarqube_network
#       - no_internet

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  postgresql:
  postgresql_data:

networks:
  sonarqube_network:
    driver: bridge
  no_internet:
    driver: bridge
    internal: true